#!/usr/bin/env bash
# A script that displays information about the subdomains.
my_dn=(www lb-01 web-01 web-02)
if [ "$#" -eq 1 ]
then
	for dn in "${my_dn[@]}"
	do
		dig $dn."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -vvar="$dn" '{print "The subdomain " var " is a " $4 " record and points to " $5}'
	done
elif [ "$#" -eq 2 ]
then
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk -vver="$2" '{print "The subdomain " var " is a " $4 " record and points to " $5}'
fi
