#!/usr/bin/env bash
# This script transfer a file from a client to a server.
#    Requirements:
#        1. The path to the file to be transfered.
#        2. The IP of the server we want to transfer the file to.
#        3. The username scp connects with
#        4. The path to the SSH private key that scp uses.

host_check="StrictHostKeyChecking=no"
# Check if the number of arguments is equal to 5
if [[ $# -lt 3 ]]
then

	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]
then
	# Assign the cmdl argument to variables.
	path_to_file=$1
	ip=$2
	username=$3
	path_to_key=$4
	# Use the scp command to transfer the file
	scp -o "$host_check" "$path_to_file" "$username@$ip:~/"
else
	# Assign the cmdl argument to variables.
	path_to_file=$1
	ip=$2
	username=$3
	path_to_key=$4
	# Use the scp command to transfer the file
	scp -i "$path_to_key" -o host_check "$path_to_file" "$username@$ip:~/"
fi
