#!/usr/bin/env bash
# A script that configures a new Ubuntu machine to
#	Listen to port 80.
#	Returns a string "Hello world!" When querried using a GET request
#	eg curl localhost
#	redirects index to /redirect me

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
string_repl="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_repl/" /etc/nginx/sites-enabled/default
sudo service nginx start
