#!/usr/bin/env bash
# Configuration of the 404 error page.

sudo apt-get -y update
sudo apt-get install -y nginx

# Redirects a specific endpoint (eg: redirect_me to https://youtupe.com)
echo "Hello World!" | sudo tee /var/www/html/index.html

# Customized 404 message
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# The redirection site
str_rep="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/realfrankiewilson permanent;"

errorpage="\n\terror_page 404 \/404.html;\n\tlocation = 404.html {\n\troot \/usr\/share\/nginx\/html;\n\tinternal;\n\t}"
sed -i "s/server_name _;/$str_rep$errorpage/" /etc/nginx/sites-available/default

# Restart nginx server
sudo service nginx restart
