#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays the following:
#	To infinity and beyond indefinitely
#	I hate the kill command (when receiving a SIGTERM signal
#	Y U no love me?! When receiving a SIGINT signal
#	Deletes the file /var/run/myscript.pid and terminates itself
#	    when recieving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
