#!/usr/bin/env bash
# Displays lines containing the bash word, thus allowing you to easily get the
#					PID of your Bash process
# Requirements:
#				You cannot use pgrep
#				The third line of your script must b #shellcheck disable=SC2009
# shellcheck disable=SC2009
ps auxf | grep bash
