#!/usr/bin/env bash
# Displays the content of the file in /etc/passwd.
# The script displays the following:
#	username
#	user id
#	Home directory path for the user
# Requirements:
#	Must use the while loop(for and until are forbidden)

read_file="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d ':' -f1,3,6
done < "$read_file"
