#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS
# Requirements:
#	You must use the while loop (for and until are forbbiden)

awk '{print $1, $9}' apache-access.log
