#!/usr/bin/env bash
# A bash that displays the time for 12 hours and 59 minutes.
#	Displays hours from 0 to 12
#	Displays minutes from 1 to 59
#
# Requirements:
#	You must use the shile loop(for and until are forbidden)

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	min=1
	while [ $min -lt 60 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))

done

