#!/usr/bin/env bash
# Displays:
#	The content of the current directory
#	In a list format
#	Where only the part of the name after the first dash displayed
# Requirements:
#	You must use the for loop(while and until are forbidden)
#	Do not display hidden files.

var=$(ls)
for i in $var; do echo "$i" | cut -d '-' -f2; done
