#!/usr/bin/env bash
# Installs and sets up firewall
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow HTTP

sudo ufw enable
